### ISSUE TITLE
Unable to run with --prior_indvdl as gauss

### ISSUE THREAD

**Issue by code-rana** [taku-y/bmlingam#10]
Hi ,
I am facing following error while trying to run bmlingam with gauss.
Commands we have issued : 
1) bmlingam-causality --standardize_on --prior_indvdls=gauss time_2.csv
2) bmlingam-causality --standardize_off --prior_indvdls=gauss time_2.csv
3) bmlingam-causality  --prior_indvdls=gauss time_2.csv
4) bmlingam-causality --standardize_off --fix_mu_zero_off --max_c=1.0 --n_mc_samples=1000  --prior_scale=log_normal --L_cov_21s=[-0.9, -0.7, -0.5, -0.3, 0, 0.3, 0.5, 0.7, 0.9] --prior_indvdls=gauss time_2.csv --sampling_mode cache_mp8 --cs=[ 0. , 0.2, 0.4, 0.6, 0.8, 1. ]

In the 4th command, BMLingam does not take lists 'cs' and L_cov_21s.

Following is the stack trace.
`Traceback (most recent call last):
  File "/usr/local/bin/bmlingam-causality", line 18, in <module>
    bmlingam_causality_(**params)
  File "/usr/local/lib/python2.7/site-packages/bmlingam/commands/bmlingam_causality.py", line 281, in bmlingam_causality
    varnames[list(pair)]) for pair in pairs]
  File "/usr/local/lib/python2.7/site-packages/bmlingam/infer_causality.py", line 24, in infer_causality
    find_best_model(xs, hparamss, sampling_mode)
  File "/usr/local/lib/python2.7/site-packages/bmlingam/find_best_model.py", line 41, in find_best_model
    for hparams in hparamss])
  File "/usr/local/lib/python2.7/site-packages/bmlingam/bmlingam_np.py", line 56, in comp_logP
    cache, prior_indvdl, L_cov_21, df_indvdl, beta_coeff)
  File "/usr/local/lib/python2.7/site-packages/bmlingam/cache_mc.py", line 165, in fetch_mu_indvdl
    ('mu_indvdl1', prior_indvdl, L_cov_21, df_indvdl, beta_coeff)]
KeyError: ('mu_indvdl1', 'gauss', -0.9, 8.0, None)
`
Thanks for looking to the problem.

**Comment by taku-y** [comment]
@abhishekscript Thanks for reporting. Could you try the code in `develop` branch? And you might need to use quatations for passing list arguments: 

```console
bmlingam-causality --L_cov_21s="[-0.9, -0.7, -0.5, -0.3, 0, 0.3, 0.5, 0.7, 0.9]" time_2.csv
```

**Comment by code-rana** [comment]
@taku-y I am trying develop branch but could not figure out how do I run it now? 
I have tried running `python bmlingam_causality.py` does not seems to work.
Thanks

**Comment by taku-y** [comment]
The following command might work:

```
git clone https://github.com/taku-y/bmlingam.git
cd bmlingam
git checkout -b develop origin/develop
python setup.py bdist_wheel --universal
cd dist
WHEEL=`ls .`
echo $WHEEL # show wheel filename for check
pip install --user $WHEEL
```

**Comment by code-rana** [comment]
Hi,
Using dev branch still not working.
Below is the issued command:
bmlingam-causality --prior_indvdl='gauss' --L_cov_21s="[-0.9, -0.7, -0.5, -0.3, 0, 0.3, 0.5, 0.7, 0.9]" time_2.csv

err : `KeyError: ('mu_indvdl1', 'gauss', -0.9, 8.0, None)`

OR

What are all the hyperparameters that are required to run BMLINGAM with prior_indvdl = "gauss"

Thanks

**Comment by taku-y** [comment]
Thanks. I got the same error. I will check this.
